id: apache-apisix-panel

info:
  name: Apache APISIX Login Panel - Detect
  author: pikpikcu,righettod
  severity: info
  description: An Apache APISIX login panel was detected.
  classification:
    cwe-id: CWE-200
    cpe: cpe:2.3:a:apache:apisix:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: apisix
    vendor: apache
    fofa-query: title="Apache APISIX Dashboard"
  tags: apache,apisix,panel,login,detect

http:
  - method: GET
    path:
      - "{{BaseURL}}/user/login?redirect=%2F"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<title>Apache APISIX Dashboard</title>'

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: header
        group: 1
        regex:
          - '(?i)Server:\s+APISIX\/([0-9.]+)'
# digest: 490a00463044022077db8164de460b6d9fad9c437f6f20ddff3d1130da4410d3e8fef855a71f69cc02205e85b466ed5fc18cbf90faa089c1beeae3b91c11e43f89454ab0b3eca85e9f73:922c64590222798bb761d5b6d8e72950