services:
  subfinder:
    image: projectdiscovery/subfinder
    command: -silent -d ${DOMAIN} -o /app/data/${DOMAIN_DIR}/subfinder_output.txt
    environment:
      - CENSYS_API_ID=${CENSYS_API_ID}
      - CENSYS_API_SECRET=${CENSYS_API_SECRET}
      - SHODAN_API_KEY=${SHODAN_API_KEY}
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - FULLHUNT_API_KEY=${FULLHUNT_API_KEY}
    volumes:
      - ./data:/app/data
    networks:
      - shared_network

  httpx:
    image: projectdiscovery/httpx
    command: -silent -l /app/data/${DOMAIN_DIR}/final_subdomains.txt -o /app/data/${DOMAIN_DIR}/live_hosts.txt
    volumes:
      - ./data:/app/data
    networks:
      - shared_network

  gau:
    image: sxcurity/gau
    command: ${DOMAIN} --subs --threads 5 --providers wayback,commoncrawl,otx,urlscan --o /app/data/${DOMAIN_DIR}/urls.txt
    volumes:
      - ./data:/app/data
    networks:
      - shared_network

  arjun:
    image: ./arjun
    command: -i /app/data/${DOMAIN_DIR}/urls.txt -o /app/data/${DOMAIN_DIR}/arjun_output.txt
    volumes:
      - ./data:/app/data
    networks:
      - shared_network

  dalfox:
    image: hahwul/dalfox
    command: file /app/data/${DOMAIN_DIR}/arjun_output.txt --silence --no-spinner -o /app/data/${DOMAIN_DIR}/dalfox_output.txt
    volumes:
      - ./data:/app/data
    networks:
      - shared_network

  getjs:
    image: ./getjs
    command: --input /app/data/${DOMAIN_DIR}/urls.txt --output /app/data/${DOMAIN_DIR}/js_urls.txt
    volumes:
      - ./data:/app/data
    networks:
      - shared_network

  paramspider:
    image: ./paramspider
    command: -d ${DOMAIN} -s > /app/data/${DOMAIN_DIR}/params.txt
    volumes:
      - ./data:/app/data
    networks:
      - shared_network

  nuclei:
    image: projectdiscovery/nuclei
    command: -silent -l /app/data/${DOMAIN_DIR}/live_hosts.txt -t /root/nuclei-templates -o /app/data/${DOMAIN_DIR}/nuclei_output.txt -rl 50 -c 25
    volumes:
      - ./data:/app/data
      - ./config/nuclei:/root/nuclei-templates
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge

