# Nuclei scan profile for scanning aws ACLs

code: true # enable code templates

tags:
  - aws-cloud-config # filter templates with "aws-cloud-config" tags

var:
  - region=us-east-1 # template input for "region" variable