id: deprecated-tls

info:
  name: Deprecated TLS Detection
  author: righettod,forgedhallpass
  severity: info
  reference:
    - https://ssl-config.mozilla.org/#config=intermediate
  description: |
    Both TLS 1.1 and SSLv3 are deprecated in favor of stronger encryption.
  remediation: |
    Update the web server's TLS configuration to disable TLS 1.1 and SSLv3.
  metadata:
    max-request: 3
    shodan-query: ssl.version:sslv2 ssl.version:sslv3 ssl.version:tlsv1 ssl.version:tlsv1.1
  tags: ssl,tls

ssl:
  - address: "{{Host}}:{{Port}}"
    min_version: tls11
    max_version: tls11

    extractors:
      - type: json
        name: tls_1.1
        json:
          - " .tls_version"

  - address: "{{Host}}:{{Port}}"
    min_version: tls10
    max_version: tls10

    extractors:
      - type: json
        name: tls_1.0
        json:
          - " .tls_version"

  - address: "{{Host}}:{{Port}}"
    min_version: ssl30
    max_version: ssl30

    extractors:
      - type: json
        name: ssl_3.0
        json:
          - " .tls_version"
# digest: 490a00463044022025cdfdc1eae1340e9d512e1e3b656b0cf356bc434ad0f011fbfa02bb502c4afa022037027e15824922e3f64c641c41b2beab0311f255e2d84e5b4dd1bebff20e944e:922c64590222798bb761d5b6d8e72950