id: flexbe-takeover

info:
  name: Flexbe Subdomain Takeover
  author: 0x_Akoko
  severity: high
  description: Flexbe takeover was detected.
  reference:
    - https://web.archive.org/web/20211002185648/https://github.com/EdOverflow/can-i-take-over-xyz/issues/237
    - https://help.flexbe.com/domains/
  metadata:
    max-request: 1
  tags: takeover,flexbe

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - Host != ip

      - type: word
        condition: and
        words:
          - "Domain isn't configured"
          - "flexbe"

      - type: status
        status:
          - 404
# digest: 4a0a00473045022100b0eb04edf08bb3be7f7019dc369fb2ce05a757eba9f8b0c43ad2ba6a99ce74a40220530f5f0dd9ad2ff3de1282b65b91678c0e2b2056086e1bcbae94064711075b51:922c64590222798bb761d5b6d8e72950