id: microfocus-iprint-detect

info:
  name: Micro Focus iPrint Appliance - Detect
  author: righettod
  severity: info
  description: |
    Micro Focus iPrint Appliance was detected.
  reference:
    - https://www.opentext.com/products/enterprise-server
  metadata:
    max-request: 1
    verified: true
    shodan-query: http.html:"Micro Focus iPrint Appliance"
  tags: tech,microfocus,detect

http:
  - method: GET
    path:
      - "{{BaseURL}}/welcome/"

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains_any(to_lower(body), "micro focus iprint appliance", "/ippdocs/clients/", "micro focus iprint", "iprint appliance")'
        condition: and

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '(?i)/welcome/css/core([0-9]+).css'
# digest: 4b0a00483046022100921c5db244930261b6ff309507cc3c59d04a95b5c6bd4ee6dbf7a976efc056f9022100c763c232c6e0063fa9870f97ae6d91ffeef60da3cead4fe2e61cd8acc9d5a59a:922c64590222798bb761d5b6d8e72950