id: cacti-panel

info:
  name: Cacti Login Panel - Detect
  author: geeknik,daffainfo
  severity: info
  description: Cacti login panel was detected.
  reference:
    - https://www.cacti.net/
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:cacti:cacti:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    product: cacti
    vendor: cacti
    shodan-query: http.favicon.hash:-1797138069
    fofa-query: icon_hash="-1797138069"
  tags: cacti,login,panel,detect

http:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/cacti/"

    stop-at-first-match: true

    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - "<title>Login to Cacti</title>"
          - "The Cacti Group"
        condition: or

      - type: regex
        part: header
        regex:
          - Cacti+

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "<div class='versionInfo'>Version (.*) |"
# digest: 4a0a00473045022100b3110f2d77b3f6513cc8f7e915660505f5f1414f89715d1fc1a562bde90075fa02201dcff79552b3f5d1622fc45bda5868f3a4b43b6bc5edf01210dc46a04630f1a6:922c64590222798bb761d5b6d8e72950