id: jfrog-login

info:
  name: JFrog Login Panel - Detect
  author: dhiyaneshDK
  severity: info
  description: |
    JFrog login panel was detected.
  reference:
    - https://www.exploit-db.com/ghdb/6797
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: http.title:"JFrog"
  tags: panel,jfrog,edb,detect,login

http:
  - method: GET
    path:
      - '{{BaseURL}}/ui/login/'
      - '{{BaseURL}}/ui/favicon.ico'

    stop-at-first-match: true
    matchers:
      - type: dsl
        dsl:
          - 'status_code==200 && contains(body, "<title>JFrog")'
          - "status_code==200 && (\"-595620639\" == mmh3(base64_py(body)))"
        condition: or
# digest: 4a0a004730450221009cfe5c81bde3f5c9462974f80c97205e62b24f03aab1a1893ca852fc0b0b49a802201c6f8e2531a0dc3974eb9f8b284db5527b43eaa7041e2eddbe10753137f5931f:922c64590222798bb761d5b6d8e72950