id: kiwitcms-login

info:
  name: Kiwi TCMS Login Panel - Detect
  author: pdteam
  severity: info
  description: Kiwi TCMS login panel was detected.
  reference:
    - https://kiwitcms.org
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:kiwitcms:kiwi_tcms:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: kiwi_tcms
    shodan-query: title:"Kiwi TCMS - Login" http.favicon.hash:-1909533337
    vendor: kiwitcms
  tags: kiwitcms,panel

http:
  - method: GET
    path:
      - "{{BaseURL}}/accounts/login/"

    matchers:
      - type: word
        words:
          - "Kiwi TCMS"

    extractors:
      - type: regex
        group: 1
        regex:
          - "Version ([0-9.]+)"
# digest: 4b0a00483046022100c7e0445fb0c4273073704f89e15d3964d3730fa6c57a6d21ae98ba39406c076102210096a4c3868ade5124d38d7a8312bcbd096227b224884baaef2d97163e6b82c9f0:922c64590222798bb761d5b6d8e72950