id: microfocus-lifecycle-panel

info:
  name: Micro Focus Application Lifecycle Management - Panel
  author: righettod
  severity: info
  description: |
    Micro Focus Application Lifecycle Management login panel was detected.
  reference:
    - https://www.opentext.com/products/alm-quality-center
  metadata:
    max-request: 1
    verified: true
    shodan-query: http.html:"Micro Focus Application Lifecycle Management"
  tags: panel,microfocus,login,detect

http:
  - method: GET
    path:
      - "{{BaseURL}}/qcbin/"

    redirects: true
    max-redirects: 2

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains_any(to_lower(body), "micro focus application lifecycle management", "<div class=\"alm_name\">application lifecycle", "<p class=\"alm_header\">application lifecycle")'
        condition: and

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '(?i)Micro\s+Focus\s+Application\s+Lifecycle\s+Management\s+([0-9.]+)'
# digest: 490a004630440220758324cb4cece38090221807411012b6414e7a7729f640252d7b6a10d86b4c0602202f1bbeb2e1678a36e27b99fd4fd3e9a355d303f66ac8b76e11278764fb694520:922c64590222798bb761d5b6d8e72950