id: microfocus-vibe-panel

info:
  name: Micro Focus Vibe Login Panel - Detect
  author: ritikchaddha,righettod
  severity: info
  description: Micro Focus Vibe login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:microfocus:vibe:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: vibe
    shodan-query: http.html:"Micro Focus Vibe"
    vendor: microfocus
    verified: true
  tags: panel,microfocus,vibe

http:
  - method: GET
    path:
      - "{{BaseURL}}/ssf/s/portalLogin"

    host-redirects: true
    max-redirects: 2

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Micro Focus Vibe"
          - "baseVibeUrl"
        condition: and

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '(?i)Copyright\s+([0-9-]+)\s+Micro\s+Focus'
# digest: 4a0a00473045022100f02b5a7248ba65a3f82f4154f6b10af010264386f1a51a80405e9fc0140dde0502206a992f6203e0788927739e360ce495a8382839cc087edea73c633118e492ba52:922c64590222798bb761d5b6d8e72950