id: microfocus-admin-server

info:
  name: Micro Focus Enterprise Server Admin Panel - Detect
  author: theabhinavgaur,righettod
  severity: info
  description: Micro Focus Enterprise Server Admin panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:microfocus:enterprise_server:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: enterprise_server
    shodan-query: Micro Focus DSD
    vendor: microfocus
    verified: true
  tags: panel,microfocus,detect,login

http:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/nps/servlet/portalservice"
      - "{{BaseURL}}/nds"
      - "{{BaseURL}}/_LOGIN_SERVER_"

    stop-at-first-match: true

    redirects: true
    max-redirects: 2

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200 && contains(to_lower(header), "micro focus dsd")'
          - 'status_code == 200 && contains_any(to_lower(body), "micro focus imanager", "micro focus imonitor", "micro focus remote manager", "micro focus open enterprise server")'
        condition: or

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '(?i)Micro\s+Focus\s+Open\s+Enterprise\s+Server\s+([A-Z0-9\s]+)'
          - '(?i)Copyright\s+([0-9]+)\s+Micro\s+Focus'
# digest: 4a0a004730450221008e8de980426ff5dfbe891462f66adba778378809ee555a753acd392e6e42f3120220736941a25c53cc07f48d8b31ded16956e7272d61407784ebd5b6faf86d43a70c:922c64590222798bb761d5b6d8e72950