id: ms-exchange-web-service

info:
  name: Microsoft Exchange Web Service - Detect
  author: bhutch,userdehghani
  severity: info
  description: |
    Microsoft Exchange Web Services was detected.
  reference:
    - https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/start-using-web-services-in-exchange
    - https://pentestlab.blog/tag/ews/
  classification:
    cpe: cpe:2.3:a:microsoft:exchange_server:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: exchange_server
    shodan-query: http.favicon.hash:1768726119
    vendor: microsoft
    verified: true
  tags: ms,microsoft,exchange,tech

http:
  - method: GET
    path:
      - "{{BaseURL}}/EWS/Exchange.asmx"
      - "{{BaseURL}}/owa/service.svc"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: regex
        part: header
        regex:
          - "(?i)(X-Owa-Version:)"

      - type: status
        status:
          - 401
          - 302

    extractors:
      - type: kval
        kval:
          - x_owa_version
# digest: 4b0a00483046022100fb3512635763556b898da7ebbc54996873117953a7ba2fbc3b876c9a8a133c94022100e38b042a828cb26dcee5a24ebc661d61e01dba07dc2265fe1e5315b99ef39ecb:922c64590222798bb761d5b6d8e72950