id: netscaler-aaa-login

info:
  name: NetScaler AAA Login Panel - Detect
  author: dhiyaneshDk,righettod
  severity: info
  description: NetScaler AAA login panel was detected.
  reference:
    - https://www.exploit-db.com/ghdb/6898
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:citrix:netscaler:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: netscaler
    vendor: citrix
  tags: panel,netscaler,login,edb,citrix,detect

http:
  - method: GET
    path:
      - '{{BaseURL}}/logon/LogonPoint/tmindex.html'

    matchers:
      - type: word
        words:
          - "NetScaler AAA</title>"
          - "_ctxstxt_NetscalerAAA"
        condition: or
# digest: 4b0a00483046022100fc8390a0699abae759299064c59fc5ac4a3e0fda101ec74ba62d8362437ea339022100a02a6c73d54ef2e5655e15c3526ff0d9e2c91abbc96e47cf045c71e19c51618a:922c64590222798bb761d5b6d8e72950