id: uptime-kuma-panel

info:
  name: Uptime Kuma - Panel
  author: irshad ahamed
  severity: info
  description: |
    Realtime website and application monitoring tool
  reference:
    - https://github.com/louislam/uptime-kuma
    - https://github.com/louislam/uptime-kuma/wiki
  metadata:
    max-request: 1
    shodan-query: title:"Uptime Kuma"
    verified: true
  tags: uptime,kuma,panel,login,detect

http:
  - method: GET
    path:
      - "{{BaseURL}}/dashboard"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Uptime Kuma</title>'

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100ebe940aa6e53fd44bcd7be03b75902f7ce7cb1bfe215dd4723f649ff99e1d778022042ca248ccf5749cc7c89884b88353eff6869ea026ddeec90a7c4d51464b5287c:922c64590222798bb761d5b6d8e72950