id: cloudflare-rocketloader-htmli

info:
  name: Cloudflare Rocket Loader - HTML Injection
  author: j3ssie
  severity: unknown
  description: |
    The Rocket Loader feature in Cloudflare allow attackers to inject arbitrary HTML into the website. This can be used to perform various attacks such as phishing, defacement, etc.
  remediation: Disable the rocket loader or Add a CSP header to fix this issue.
  reference:
    - https://developers.cloudflare.com/speed/optimization/content/rocket-loader/enable/
    - https://developers.cloudflare.com/fundamentals/reference/policies-compliances/content-security-policies/#product-requirements
  metadata:
    verified: true
    max-request: 1
  tags: misconfig,cloudflare,htmli

http:
  - method: GET
    path:
      - "{{BaseURL}}/cdn-cgi/image/width=1000,format=auto/https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/cloudflare.svg"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'Cloudflare'
          - '<svg'
          - 'M16.5088 16.8447c.1475-.5068.0908-.9707-.1553-1.3154-.2246-.3164-.6045-.499-1.0615-.5205l-'
          - '1475.5068-.0918.9707.1543 1.3164.2256.3164.6055.498'
        condition: and

      - type: word
        part: header
        words:
          - 'image/svg+xml'

      - type: status
        status:
          - 200
# digest: 4a0a0047304502204d31387c924b19c1fe6ea3ac22a8c991cac1bee85fff7482d398b5817711313b022100f6125416aaf2f9132f5aac7ac183e6f855f343124e33e429d10bb07af5553fdb:922c64590222798bb761d5b6d8e72950