id: CVE-2024-2340

info:
  name: Avada < 7.11.7 - Information Disclosure
  author: t3l3machus
  severity: medium
  description: |
    The Avada theme for WordPress is vulnerable to Sensitive Information Exposure in all versions up to, and including, 7.11.6 via the '/wp-content/uploads/fusion-forms/' directory. This makes it possible for unauthenticated attackers to extract sensitive data uploaded via an Avada created form with a file upload mechanism.
  remediation: Fixed in 7.11.7
  reference:
    - https://vulners.com/wpvulndb/WPVDB-ID:507E1D07-4953-4A31-81E8-80F01F971E2A
    - https://avada.com/documentation/avada-changelog/
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/8db8bbc3-43ca-4ef5-a44d-2987c8597961?source=cve
    - https://nvd.nist.gov/vuln/detail/CVE-2024-2340
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cve-id: CVE-2024-2340
    epss-score: 0.00043
    epss-percentile: 0.08267
  metadata:
    verified: true
    max-request: 1
  tags: cve,cve2024,wp-theme,wp,wordpress,wpscan,avada,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/uploads/fusion-forms/"

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - '<title>Index of [\s\S]*title>'
          - 'fusion'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a0047304502210086a9d9e4d491bbdaf66cc96f24d32ffa31c10df273bab32f91385760014d579b022048d3aa9fe3beec267bb552efa870d3ac9644d1501b28f39ab998dbef346ba1dd:922c64590222798bb761d5b6d8e72950